## Dockerfile specifico per l'esecuzione delle migrations
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20 AS base
RUN apk add --no-cache bash curl jq

WORKDIR /src
COPY . ./

RUN rm -rf /root/.dotnet/tools && \
    dotnet tool install --global dotnet-ef --version 9.0.0
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["bash", "entrypoint.migrations.sh"]
