// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trasformazioni.Data;

#nullable disable

namespace Trasformazioni.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205101230_AddGaraAttributePnrr")]
    partial class AddGaraAttributePnrr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("DataAssunzione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Reparto")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.AssegnazioneMezzo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChilometraggioFine")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ChilometraggioInizio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MezzoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("MotivoAssegnazione")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UtenteId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataFine");

                    b.HasIndex("DataInizio");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MezzoId");

                    b.HasIndex("UtenteId");

                    b.HasIndex("MezzoId", "DataFine");

                    b.HasIndex("UtenteId", "DataInizio");

                    b.HasIndex("MezzoId", "DataInizio", "DataFine")
                        .HasDatabaseName("IX_AssegnazioniMezzi_Mezzo_Periodi");

                    b.ToTable("AssegnazioniMezzi", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.DocumentoGara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaricatoDaUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("DimensioneBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("GaraId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IntegrazioneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUploadCompleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LottoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PathMinIO")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PreventivoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaricatoDaUserId")
                        .HasDatabaseName("IX_DocumentiGara_CaricatoDaUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataCaricamento")
                        .HasDatabaseName("IX_DocumentiGara_DataCaricamento");

                    b.HasIndex("GaraId")
                        .HasDatabaseName("IX_DocumentiGara_GaraId");

                    b.HasIndex("IntegrazioneId")
                        .HasDatabaseName("IX_DocumentiGara_IntegrazioneId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsUploadCompleto")
                        .HasDatabaseName("IX_DocumentiGara_IsUploadCompleto")
                        .HasFilter("\"IsUploadCompleto\" = false");

                    b.HasIndex("LottoId")
                        .HasDatabaseName("IX_DocumentiGara_LottoId");

                    b.HasIndex("PathMinIO")
                        .HasDatabaseName("IX_DocumentiGara_PathMinIO");

                    b.HasIndex("PreventivoId")
                        .HasDatabaseName("IX_DocumentiGara_PreventivoId");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("IX_DocumentiGara_TipoDocumentoId");

                    b.HasIndex("GaraId", "TipoDocumentoId")
                        .HasDatabaseName("IX_DocumentiGara_GaraId_TipoDocumentoId");

                    b.HasIndex("LottoId", "TipoDocumentoId")
                        .HasDatabaseName("IX_DocumentiGara_LottoId_TipoDocumentoId");

                    b.ToTable("DocumentiGara", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.ElaborazioneLotto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LottoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MotivazioneAdattamento")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("PrezzoDesiderato")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PrezzoRealeUscita")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LottoId")
                        .IsUnique()
                        .HasDatabaseName("IX_ElaborazioniLotti_LottoId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("PrezzoDesiderato")
                        .HasDatabaseName("IX_ElaborazioniLotti_PrezzoDesiderato");

                    b.HasIndex("PrezzoRealeUscita")
                        .HasDatabaseName("IX_ElaborazioniLotti_PrezzoRealeUscita");

                    b.ToTable("ElaborazioniLotti", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Gara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bando")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CIG")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CUP")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ChiusaDaUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CodiceGara")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CriterioAggiudicazione")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DataChiusuraManuale")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataInizioPresentazioneOfferte")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataPubblicazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataTerminePresentazioneOfferte")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataTermineRichiestaChiarimenti")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("DenominazioneIniziativa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EnteAppaltante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ImportoTotaleStimato")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsChiusaManualmente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkPiattaforma")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MotivoChiusuraManuale")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NomePuntoOrdinante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PNRR")
                        .HasColumnType("boolean");

                    b.Property<string>("Procedura")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RDO")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Regione")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelefonoPuntoOrdinante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CIG")
                        .HasDatabaseName("IX_Gare_CIG");

                    b.HasIndex("ChiusaDaUserId");

                    b.HasIndex("CodiceGara")
                        .IsUnique()
                        .HasDatabaseName("IX_Gare_CodiceGara");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataPubblicazione")
                        .HasDatabaseName("IX_Gare_DataPubblicazione");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Stato")
                        .HasDatabaseName("IX_Gare_Stato");

                    b.HasIndex("Stato", "DataPubblicazione")
                        .HasDatabaseName("IX_Gare_Stato_DataPubblicazione");

                    b.ToTable("Gare", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Lotto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodiceLotto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DataInizioEsameEnte")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataScadenzaContratto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataStipulaContratto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DurataContratto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Fatturazione")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GaraId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GiorniFornitura")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ImportoBaseAsta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkPiattaforma")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MotivoRifiuto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OperatoreAssegnatoId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<decimal?>("Quotazione")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("RichiedeFideiussione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataInizioEsameEnte")
                        .HasDatabaseName("IX_Lotti_DataInizioEsameEnte");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OperatoreAssegnatoId")
                        .HasDatabaseName("IX_Lotti_OperatoreAssegnatoId");

                    b.HasIndex("Stato")
                        .HasDatabaseName("IX_Lotti_Stato");

                    b.HasIndex("GaraId", "CodiceLotto")
                        .IsUnique()
                        .HasDatabaseName("IX_Lotti_GaraId_CodiceLotto");

                    b.HasIndex("GaraId", "Stato")
                        .HasDatabaseName("IX_Lotti_GaraId_Stato");

                    b.ToTable("Lotti", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Mezzo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Anno")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Chilometraggio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DataAcquisto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataFineNoleggio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataImmatricolazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataInizioNoleggio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataScadenzaAssicurazione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataScadenzaRevisione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("DeviceIMEI")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DevicePhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SocietaNoleggio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Stato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Targa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoProprieta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataScadenzaAssicurazione");

                    b.HasIndex("DataScadenzaRevisione");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Stato");

                    b.HasIndex("Targa")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("TipoProprieta");

                    b.HasIndex("Marca", "Modello");

                    b.ToTable("Mezzi", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Notifica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DataInvioEmail")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataLettura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("DestinatarioUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid?>("GaraId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInviataEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLetta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("LottoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid?>("ScadenzaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Notifiche_CreatedAt");

                    b.HasIndex("DataLettura")
                        .HasDatabaseName("IX_Notifiche_DataLettura");

                    b.HasIndex("DestinatarioUserId")
                        .HasDatabaseName("IX_Notifiche_DestinatarioUserId");

                    b.HasIndex("GaraId")
                        .HasDatabaseName("IX_Notifiche_GaraId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsInviataEmail")
                        .HasDatabaseName("IX_Notifiche_IsInviataEmail");

                    b.HasIndex("IsLetta")
                        .HasDatabaseName("IX_Notifiche_IsLetta");

                    b.HasIndex("LottoId")
                        .HasDatabaseName("IX_Notifiche_LottoId");

                    b.HasIndex("ScadenzaId")
                        .HasDatabaseName("IX_Notifiche_ScadenzaId");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_Notifiche_Tipo");

                    b.HasIndex("DestinatarioUserId", "CreatedAt")
                        .HasDatabaseName("IX_Notifiche_DestinatarioUserId_CreatedAt");

                    b.HasIndex("DestinatarioUserId", "IsLetta")
                        .HasDatabaseName("IX_Notifiche_DestinatarioUserId_IsLetta");

                    b.HasIndex("IsInviataEmail", "CreatedAt")
                        .HasDatabaseName("IX_Notifiche_IsInviataEmail_CreatedAt");

                    b.ToTable("Notifiche", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.PartecipanteLotto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsAggiudicatario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsScartatoDallEnte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LottoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("OffertaEconomica")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SoggettoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsAggiudicatario")
                        .HasDatabaseName("IX_PartecipantiLotti_IsAggiudicatario");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsScartatoDallEnte")
                        .HasDatabaseName("IX_PartecipantiLotti_IsScartatoDallEnte");

                    b.HasIndex("LottoId")
                        .HasDatabaseName("IX_PartecipantiLotti_LottoId");

                    b.HasIndex("SoggettoId")
                        .HasDatabaseName("IX_PartecipantiLotti_SoggettoId");

                    b.HasIndex("LottoId", "IsAggiudicatario")
                        .HasDatabaseName("IX_PartecipantiLotti_LottoId_IsAggiudicatario");

                    b.HasIndex("LottoId", "IsScartatoDallEnte")
                        .HasDatabaseName("IX_PartecipantiLotti_LottoId_IsScartatoDallEnte");

                    b.ToTable("PartecipantiLotti", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Preventivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DataRicezione")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataRichiesta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("GiorniAutoRinnovo")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ImportoOfferto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSelezionato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LottoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SoggettoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataScadenza")
                        .HasDatabaseName("IX_Preventivi_DataScadenza");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsSelezionato")
                        .HasDatabaseName("IX_Preventivi_IsSelezionato");

                    b.HasIndex("LottoId")
                        .HasDatabaseName("IX_Preventivi_LottoId");

                    b.HasIndex("SoggettoId")
                        .HasDatabaseName("IX_Preventivi_SoggettoId");

                    b.HasIndex("Stato")
                        .HasDatabaseName("IX_Preventivi_Stato");

                    b.HasIndex("DataScadenza", "Stato")
                        .HasDatabaseName("IX_Preventivi_DataScadenza_Stato");

                    b.HasIndex("LottoId", "Stato")
                        .HasDatabaseName("IX_Preventivi_LottoId_Stato");

                    b.ToTable("Preventivi", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.RichiestaIntegrazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("DataRichiestaEnte")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataRispostaAzienda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("DocumentoRichiestaPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocumentoRispostaPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsChiusa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LottoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("NomeFileRichiesta")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomeFileRisposta")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("NumeroProgressivo")
                        .HasColumnType("integer");

                    b.Property<string>("RispostaDaUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("TestoRichiestaEnte")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("TestoRispostaAzienda")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataRichiestaEnte")
                        .HasDatabaseName("IX_RichiesteIntegrazione_DataRichiestaEnte");

                    b.HasIndex("IsChiusa")
                        .HasDatabaseName("IX_RichiesteIntegrazione_IsChiusa");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LottoId")
                        .HasDatabaseName("IX_RichiesteIntegrazione_LottoId");

                    b.HasIndex("RispostaDaUserId")
                        .HasDatabaseName("IX_RichiesteIntegrazione_RispostaDaUserId");

                    b.HasIndex("IsChiusa", "DataRichiestaEnte")
                        .HasDatabaseName("IX_RichiesteIntegrazione_IsChiusa_DataRichiestaEnte");

                    b.HasIndex("LottoId", "IsChiusa")
                        .HasDatabaseName("IX_RichiesteIntegrazione_LottoId_IsChiusa");

                    b.HasIndex("LottoId", "NumeroProgressivo")
                        .IsUnique()
                        .HasDatabaseName("IX_RichiesteIntegrazione_LottoId_NumeroProgressivo");

                    b.ToTable("RichiesteIntegrazione", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Scadenza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DataCompletamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("GaraId")
                        .HasColumnType("uuid");

                    b.Property<int>("GiorniPreavviso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsAutomatica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCompletata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LottoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("PreventivoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataScadenza")
                        .HasDatabaseName("IX_Scadenze_DataScadenza");

                    b.HasIndex("GaraId")
                        .HasDatabaseName("IX_Scadenze_GaraId");

                    b.HasIndex("IsAutomatica")
                        .HasDatabaseName("IX_Scadenze_IsAutomatica");

                    b.HasIndex("IsCompletata")
                        .HasDatabaseName("IX_Scadenze_IsCompletata");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LottoId")
                        .HasDatabaseName("IX_Scadenze_LottoId");

                    b.HasIndex("PreventivoId")
                        .HasDatabaseName("IX_Scadenze_PreventivoId");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_Scadenze_Tipo");

                    b.HasIndex("GaraId", "IsCompletata")
                        .HasDatabaseName("IX_Scadenze_GaraId_IsCompletata");

                    b.HasIndex("IsCompletata", "DataScadenza")
                        .HasDatabaseName("IX_Scadenze_IsCompletata_DataScadenza");

                    b.HasIndex("LottoId", "IsCompletata")
                        .HasDatabaseName("IX_Scadenze_LottoId_IsCompletata");

                    b.HasIndex("DataScadenza", "GiorniPreavviso", "IsCompletata")
                        .HasDatabaseName("IX_Scadenze_DataScadenza_GiorniPreavviso_IsCompletata");

                    b.ToTable("Scadenze", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Soggetto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CAP")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CodiceIPA")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("CodiceInterno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodiceSDI")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Cognome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CondizioniPagamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Denominazione")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFornitore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("NaturaGiuridica")
                        .HasColumnType("integer");

                    b.Property<string>("Nazione")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeVia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NumeroCivico")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PEC")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PartitaIVA")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Referente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ScontoPartner")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipoSoggetto")
                        .HasColumnType("integer");

                    b.Property<string>("TipoVia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodiceFiscale");

                    b.HasIndex("CodiceInterno")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PartitaIVA");

                    b.HasIndex("TipoSoggetto", "IsCliente", "IsFornitore");

                    b.ToTable("Soggetti", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodiceRiferimento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Area")
                        .HasDatabaseName("IX_TipiDocumento_Area");

                    b.HasIndex("CodiceRiferimento")
                        .HasDatabaseName("IX_TipiDocumento_CodiceRiferimento");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_TipiDocumento_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_TipiDocumento_IsDeleted");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("IX_TipiDocumento_IsSystem");

                    b.HasIndex("Area", "IsDeleted")
                        .HasDatabaseName("IX_TipiDocumento_Area_IsDeleted");

                    b.HasIndex("Nome", "Area")
                        .IsUnique()
                        .HasDatabaseName("IX_TipiDocumento_Nome_Area")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("TipiDocumento", (string)null);
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.ValutazioneLotto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("DataValutazioneEconomica")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataValutazioneTecnica")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool?>("EconomicaApprovata")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LottoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MotivoRifiutoEconomico")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MotivoRifiutoTecnico")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NoteEconomiche")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NoteTecniche")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool?>("TecnicaApprovata")
                        .HasColumnType("boolean");

                    b.Property<string>("ValutatoreEconomicoId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ValutatoreTecnicoId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataValutazioneEconomica")
                        .HasDatabaseName("IX_ValutazioniLotti_DataValutazioneEconomica");

                    b.HasIndex("DataValutazioneTecnica")
                        .HasDatabaseName("IX_ValutazioniLotti_DataValutazioneTecnica");

                    b.HasIndex("EconomicaApprovata")
                        .HasDatabaseName("IX_ValutazioniLotti_EconomicaApprovata");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LottoId")
                        .IsUnique()
                        .HasDatabaseName("IX_ValutazioniLotti_LottoId");

                    b.HasIndex("TecnicaApprovata")
                        .HasDatabaseName("IX_ValutazioniLotti_TecnicaApprovata");

                    b.HasIndex("ValutatoreEconomicoId")
                        .HasDatabaseName("IX_ValutazioniLotti_ValutatoreEconomicoId");

                    b.HasIndex("ValutatoreTecnicoId")
                        .HasDatabaseName("IX_ValutazioniLotti_ValutatoreTecnicoId");

                    b.ToTable("ValutazioniLotti", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.AssegnazioneMezzo", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.Mezzo", "Mezzo")
                        .WithMany("Assegnazioni")
                        .HasForeignKey("MezzoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", "Utente")
                        .WithMany("AssegnazioniMezzi")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mezzo");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.DocumentoGara", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", "CaricatoDa")
                        .WithMany()
                        .HasForeignKey("CaricatoDaUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.Gara", "Gara")
                        .WithMany("Documenti")
                        .HasForeignKey("GaraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Trasformazioni.Models.Entities.RichiestaIntegrazione", "Integrazione")
                        .WithMany()
                        .HasForeignKey("IntegrazioneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Trasformazioni.Models.Entities.Lotto", "Lotto")
                        .WithMany("Documenti")
                        .HasForeignKey("LottoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Trasformazioni.Models.Entities.Preventivo", "Preventivo")
                        .WithMany()
                        .HasForeignKey("PreventivoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Trasformazioni.Models.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("DocumentiGara")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaricatoDa");

                    b.Navigation("Gara");

                    b.Navigation("Integrazione");

                    b.Navigation("Lotto");

                    b.Navigation("Preventivo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.ElaborazioneLotto", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.Lotto", "Lotto")
                        .WithOne("Elaborazione")
                        .HasForeignKey("Trasformazioni.Models.Entities.ElaborazioneLotto", "LottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lotto");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Gara", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", "ChiusaDa")
                        .WithMany()
                        .HasForeignKey("ChiusaDaUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChiusaDa");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Lotto", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.Gara", "Gara")
                        .WithMany("Lotti")
                        .HasForeignKey("GaraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", "OperatoreAssegnato")
                        .WithMany()
                        .HasForeignKey("OperatoreAssegnatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gara");

                    b.Navigation("OperatoreAssegnato");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Notifica", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.Gara", "Gara")
                        .WithMany()
                        .HasForeignKey("GaraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Trasformazioni.Models.Entities.Lotto", "Lotto")
                        .WithMany()
                        .HasForeignKey("LottoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Trasformazioni.Models.Entities.Scadenza", "Scadenza")
                        .WithMany()
                        .HasForeignKey("ScadenzaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Destinatario");

                    b.Navigation("Gara");

                    b.Navigation("Lotto");

                    b.Navigation("Scadenza");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.PartecipanteLotto", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.Lotto", "Lotto")
                        .WithMany("Partecipanti")
                        .HasForeignKey("LottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.Soggetto", "Soggetto")
                        .WithMany()
                        .HasForeignKey("SoggettoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lotto");

                    b.Navigation("Soggetto");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Preventivo", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.Lotto", "Lotto")
                        .WithMany("Preventivi")
                        .HasForeignKey("LottoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.Soggetto", "Soggetto")
                        .WithMany()
                        .HasForeignKey("SoggettoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lotto");

                    b.Navigation("Soggetto");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.RichiestaIntegrazione", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.Lotto", "Lotto")
                        .WithMany("RichiesteIntegrazione")
                        .HasForeignKey("LottoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", "RispostaDa")
                        .WithMany()
                        .HasForeignKey("RispostaDaUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lotto");

                    b.Navigation("RispostaDa");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Scadenza", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.Gara", "Gara")
                        .WithMany()
                        .HasForeignKey("GaraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Trasformazioni.Models.Entities.Lotto", "Lotto")
                        .WithMany()
                        .HasForeignKey("LottoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Trasformazioni.Models.Entities.Preventivo", "Preventivo")
                        .WithMany()
                        .HasForeignKey("PreventivoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Gara");

                    b.Navigation("Lotto");

                    b.Navigation("Preventivo");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.ValutazioneLotto", b =>
                {
                    b.HasOne("Trasformazioni.Models.Entities.Lotto", "Lotto")
                        .WithOne("Valutazione")
                        .HasForeignKey("Trasformazioni.Models.Entities.ValutazioneLotto", "LottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", "ValutatoreEconomico")
                        .WithMany()
                        .HasForeignKey("ValutatoreEconomicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Trasformazioni.Models.Entities.ApplicationUser", "ValutatoreTecnico")
                        .WithMany()
                        .HasForeignKey("ValutatoreTecnicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lotto");

                    b.Navigation("ValutatoreEconomico");

                    b.Navigation("ValutatoreTecnico");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AssegnazioniMezzi");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Gara", b =>
                {
                    b.Navigation("Documenti");

                    b.Navigation("Lotti");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Lotto", b =>
                {
                    b.Navigation("Documenti");

                    b.Navigation("Elaborazione");

                    b.Navigation("Partecipanti");

                    b.Navigation("Preventivi");

                    b.Navigation("RichiesteIntegrazione");

                    b.Navigation("Valutazione");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.Mezzo", b =>
                {
                    b.Navigation("Assegnazioni");
                });

            modelBuilder.Entity("Trasformazioni.Models.Entities.TipoDocumento", b =>
                {
                    b.Navigation("DocumentiGara");
                });
#pragma warning restore 612, 618
        }
    }
}
